### ISSUE TITLE
[BUG] 드라이버 차량 사진 중복 API 배포 후 관련 오류 수정

### ISSUE THREAD

**Issue by Yurim222** [Mallang-Trip/Web#129]
## 🐛 어떤 버그인가요?
API가 배포 되기 전에 변경점들을 수정하였으나, 미처 생각하지 못해 발생하는 오류들입니다.

## 📌 작업 상세 내용
- [x] 드라이버 등록하기 페이지에서 발생하는 오류의 해결
- [x] 드리이버 차량 사진 등록하기 버튼 컴포넌트 수정

**Comment by DaeHee99** [comment]
@Yurim222 이거 혹시 어떻게 진행되고 있는거야?!

**Comment by Yurim222** [comment]
지금 오류는 다 수정됐고, 클릭하면 삭제되는 거까지 다 구현해서 push 해 놓은 상황이야!
그리고 사진 개수가 컴포넌트 너비를 초과하면 스크롤 생기는 거 구현하고 있었어!

**Comment by Yurim222** [comment]
스크롤 숨기고 버튼 누르면 오른쪽으로 가는 거 구현하고 있었는데, 빨리 배포가 필요한 거면 그냥 빨리 대충 만들게!

**Comment by Yurim222** [comment]
![image](https://github.com/Mallang-Trip/Web/assets/76727686/f8a7c9c0-31f4-4ec2-90ef-aa0c7c328d4c)
참고로 지금 내 로컬에서는 이런 화면인데 스크롤이 너무 안 예뻐서 고민하고 있었어

**Comment by DaeHee99** [comment]
> ![image](https://private-user-images.githubusercontent.com/76727686/347885414-f8a7c9c0-31f4-4ec2-90ef-aa0c7c328d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MTIzMzksIm5iZiI6MTcyMDcxMjAzOSwicGF0aCI6Ii83NjcyNzY4Ni8zNDc4ODU0MTQtZjhhN2M5YzAtMzFmNC00ZWMyLTkwZWYtYWEwYzdjMzI4ZDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE1MzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyM2ZlMDRlMTU2NWI4MWMyZjEwMDAxOGRlZDUyNDRlYzgyMTY0YjVmNDkzZGZmMjMxMjgwMGFkYmI4MDc4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mt58PEGTb7zld-87HXrD1q3fg74rutq8y_a5x3BImcQ) 참고로 지금 내 로컬에서는 이런 화면인데 스크롤이 너무 안 예뻐서 고민하고 있었어

스크롤바는 어차피 나중에 디자인 적용할거라서, 일단 noScrollBar로 숨겨놓으면 될 것 같아!
디자인팀에서 사진 여러장 업로드에 대한 디자인은 안해주는거지..?

**Comment by Yurim222** [comment]
아 그래? 그 건에 대해서는 전에 구글챗으로 물어봤었는데 그냥 이 대화가 끝이었어!
![image](https://github.com/Mallang-Trip/Web/assets/76727686/d51b9073-a5ed-4ba5-abca-bee5555fc029)

**Comment by DaeHee99** [comment]
일단 이미지 여러장 업로드하고 스크롤만 되도 충분할 것 같아
많이 급한건 아니니까, 내일 저녁까지 완료해주면 확인해볼게 :)

**Comment by Yurim222** [comment]
> 일단 이미지 여러장 업로드하고 스크롤만 되도 충분할 것 같아 많이 급한건 아니니까, 내일 저녁까지 완료해주면 확인해볼게 :)

응응 알겠어! 😀😀

**Comment by DaeHee99** [comment]
저거는 드라이버 프로필이라 드라이버 등록 페이지는 다를 줄 알았는데,
사실 지금 상태도 충분히 괜찮은 것 같아 ㅎㅎ

**Comment by Yurim222** [comment]
악 그렇네 그렇게 생각할 거 같아 나였어도 ㅋㅋㅋㅋㅎ
응응 알겠어! 그럼 그냥 이렇게 push 할게

**Comment by DaeHee99** [comment]
> 악 그렇네 그렇게 생각할 거 같아 나였어도 ㅋㅋㅋㅋㅎ 응응 알겠어! 그럼 그냥 이렇게 push 할게

알겠어!!! 이 이슈는 내일 저녁에 확인해볼게~
그 전에 수정 사항 있으면 바로바로 push 해줘!

**Comment by Yurim222** [comment]
넵-! 😀
